using System;

namespace RefactoringExample
{
    internal static class ReportGenerator
    {
        public static void Generate(string name, int age, double discount,
            bool isActive, DateTime reportDate, string reportType)
        {
            PrintHeader(name, reportType);
            PrintAccountInformation(age, discount, isActive, reportDate);
            PrintRecommendations(age, discount, isActive);
            PrintFooter(name, reportType);
        }

        private static void PrintHeader(string name, string reportType)
        {
            Console.WriteLine("Starting report generation...");
            Console.WriteLine(GetReportTitle(reportType));

            string header = $"Report for: {name}";
            Console.WriteLine(header);
            Console.WriteLine(new string('-', header.Length));
        }

        private static string GetReportTitle(string reportType)
        {
            return reportType switch
            {
                "detailed" => "=== DETAILED REPORT ===",
                "summary" => "=== SUMMARY REPORT ===",
                _ => "=== STANDARD REPORT ==="
            };
        }

        private static void PrintAccountInformation(int age, double discount,
            bool isActive, DateTime reportDate)
        {
            Console.WriteLine($"Age: {age}");
            Console.WriteLine($"Discount: {discount:P0}");
            Console.WriteLine($"Active status: {(isActive ? "Active" : "Inactive")}");
            Console.WriteLine($"Report date: {reportDate:yyyy-MM-dd HH:mm:ss}");

            Console.WriteLine("\nDETAILS:");
            Console.WriteLine("Account information:");
            Console.WriteLine(GetCustomerClassification(age, discount));

            if (isActive)
            {
                Console.WriteLine("Customer is currently active");
                Console.WriteLine("Last activity: " + reportDate.AddDays(-7).ToString("yyyy-MM-dd"));
            }
            else
            {
                Console.WriteLine("Customer is not active");
                Console.WriteLine("Account will be archived soon");
            }
        }

        private static string GetCustomerClassification(int age, double discount)
        {
            if (age < 25)
            {
                return discount > 0.1
                    ? "Young customer with high discount"
                    : "Young customer with standard discount";
            }

            if (age < 40)
            {
                return discount > 0.15
                    ? "Adult customer with premium discount"
                    : "Adult customer with standard discount";
            }

            return discount > 0.2
                ? "Senior customer with special discount"
                : "Senior customer with standard discount";
        }

        private static void PrintRecommendations(int age, double discount, bool isActive)
        {
            Console.WriteLine("\nRECOMMENDATIONS:");

            string? recommendation = GetRecommendation(age, discount, isActive);
            if (recommendation != null)
            {
                Console.WriteLine(recommendation);
            }
        }

        private static string? GetRecommendation(int age, double discount, bool isActive)
        {
            if (!isActive && age < 30)
            {
                return "Consider reactivation campaign for young inactive customer";
            }

            if (isActive && discount < 0.05)
            {
                return "Consider loyalty program for active customer with low discount";
            }

            if (age > 60 && discount < 0.1)
            {
                return "Consider senior discount program";
            }

            return null;
        }

        private static void PrintFooter(string name, string reportType)
        {
            Console.WriteLine("\n" + new string('=', 50));
            Console.WriteLine("Report generated by: Automated Reporting System");
            Console.WriteLine($"Generation timestamp: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            Console.WriteLine(new string('=', 50));

            if (reportType == "detailed")
            {
                Console.WriteLine("Saving detailed report to database...");
                System.Threading.Thread.Sleep(100);
                Console.WriteLine("Report saved successfully");
            }

            Console.WriteLine($"Report for {name} completed at {DateTime.Now:HH:mm:ss}");
        }
    }
}
